variables:
  URL: "https://rancher.ordbuy.com"

stages:
  - publish
  - deploydev
#  - deploystage
  - deployprod

push_image:
  stage: publish
  script:
    - npm install
    - npm run build:prod
    - 'echo "{ \"projectsDir\": \"${PWD}/jssy-projects\" }" > dev-config.json'
    - ssh-keyscan -p 29184 gitlab.ordbuy.com >> ~/.ssh/known_hosts
    - git clone ssh://git@gitlab.ordbuy.com:29184/jssy/jssy-projects.git
    - while read PROJECT; do node rebuild-components-bundle.js --config dev-config.json -- ${PROJECT}; done < <(find jssy-projects/* -maxdepth 0 -type d | sed 's/.*\///g')
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json) .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
    - docker rmi -f $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
  only:
    - /^dev$/
  tags:
    - node

deploy_to_dev:
  stage: deploydev
  script:
    - sed -i "s|{{TAG}}|$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)|g" docker-compose-dev.yml
    - rancher-compose --url $URL --access-key $ACCESS_KEY_DEV --secret-key $SECRET_KEY_DEV -p $CI_PROJECT_NAMESPACE -f docker-compose-dev.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
  environment:
    name: Jssy
    url: https://dev.booben.io/app
  only:
    - /^dev$/
  tags:
    - rancher

#deploy_to_stage:
#  stage: deploystage
#  script:
#    - sed -i "s|{{TAG}}|$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)|g" docker-compose.yml
#    - rancher-compose --url $URL --access-key $ACCESS_KEY_STAGE --secret-key $SECRET_KEY_STAGE -p $CI_PROJECT_NAMESPACE -f docker-compose-stage.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
#  environment:
#    name: Staging
#    url: https://staging.ordbuy.com
#  only:
#    - master
#  tags:
#    - rancher

deploy_to_prod:
  stage: deployprod
  before_script:
  script:
    - sed -i "s|{{TAG}}|$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)|g" docker-compose-prod.yml
    - rancher-compose --url $URL --access-key $ACCESS_KEY_DEV --secret-key $SECRET_KEY_DEV -p $CI_PROJECT_NAMESPACE -f docker-compose-prod.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
  environment:
    name: Production
    url: https://prod.booben.io/app
  only:
    - master
  when: manual
  tags:
    - rancher
