variables:
  URL: "https://rancher.ordbuy.com"
  TAG: "preview5"

stages:
  - publish
  - deploydev
#  - deploystage
#  - deployprod

push_image:
  stage: publish
  cache:
    untracked: true
    paths:
      - node_modules/
      - yarn.lock
  script:
    - yarn install
    - yarn run build
#    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json) .
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
#    - docker rmi -f $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
    - docker build -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
    - docker rmi -f $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$TAG
  only:
    - master
  tags:
    - node

deploy_to_dev:
  stage: deploydev
  script:
    - sed -i "s|{{TAG}}|$(echo $TAG)|g" docker-compose-dev.yml
    - rancher-compose --url $URL --access-key $ACCESS_KEY_DEV --secret-key $SECRET_KEY_DEV -p $CI_PROJECT_NAMESPACE -f docker-compose-dev.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
  environment:
    name: Jssy
    url: http://jssy.ordbuy.com/app/test/
  only:
    - master
  tags:
    - rancher

#deploy_to_stage:
#  stage: deploystage
#  script:
#    - sed -i "s|{{TAG}}|$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)|g" docker-compose.yml
#    - rancher-compose --url $URL --access-key $ACCESS_KEY_STAGE --secret-key $SECRET_KEY_STAGE -p $CI_PROJECT_NAMESPACE -f docker-compose-stage.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
#  environment:
#    name: Staging
#    url: https://staging.ordbuy.com
#  only:
#    - master
#  tags:
#    - rancher

#deploy_to_prod:
#  stage: deployprod
#  before_script:
#  script:
#    - sed -i "s|{{TAG}}|$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)|g" docker-compose-prod.yml
#    - rancher-compose --url $URL --access-key $ACCESS_KEY_PROD --secret-key $SECRET_KEY_PROD -p $CI_PROJECT_NAMESPACE -f docker-compose-prod.yml up $CI_PROJECT_NAME -p --force-upgrade -c -d
#  environment:
#    - name: Production
#    - url: https://ordbuy.com
#  only:
#    - tags
#  when: manual
#  tags:
#    - rancher
