env:
  global:
    - DOCKER_REPO=braincrumbs/booben

sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - rm -f package-lock.json
  - npm i -g npm

install: true
script: echo "npm test temporarily disabled"
deploy:
  provider: script
    script:
      - make bootstrap
      - make docker-build
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag booben:latest $DOCKER_REPO:latest
      - docker push $DOCKER_REPO:latest
      - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
      - docker push $DOCKER_REPO:$(sed -nr 's/.*"version":\ "(.*)",/\1/p' package.json)
